### PR TITLE
Add simple parser fuzzer

### PR DESCRIPTION
**Pull request by killercup**

### CODE REVIEW

**Comment by killercup** [comment]
Protip: If you don't have much time to contribute to a project, have a ~~computer~~ fuzzer do it for you 😉

**Comment by LeopoldArkham** [comment]
Thanks Pascal, good to see you here!

Since I have you, any outstanding API requirements you can think of? If so, feel free to mention them in #8

**Comment by markcol** [comment]
@killercup could you add documentation about how to run the fuzzing tests, or include it as part of the tests, probably ignored by default but included with a [filter](https://doc.rust-lang.org/book/second-edition/ch11-02-running-tests.html#ignore-some-tests-unless-specifically-requested).

**Comment by killercup** [comment]
@markcol this uses cargo-fuzz (`cargo install cargo-fuzz`) and its typical usage (`cargo fuzz run parse --release`). I can add a short note to the Readme.

Running the fuzzer on CI might be a nice idea, as it's a very fast fuzzer (32k iterations/s), e.g. with a timeout (`cargo fuzz run parse --release -- -max_len=4100 -max_total_time=10`). @LeopoldArkham, is that something you want?

**Comment by LeopoldArkham** [comment]
Yes, via Travis seems like the way to do it; Although I'm not certain it should fail the build... Fuzzer errors are kind of esoteric.
I could be swayed either way.

**Pull request merged**
